name: Build & Run Unit Tests

on:
  push:
    branches: [ v2_release, v2_develop ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ v2_release, v2_develop ]
    paths-ignore:
      - '**.md'
      
jobs:
  build_and_test_debug:

    runs-on: ${{ matrix.os }}
    strategy:
      # Turn off fail-fast to let all runners run even if there are errors
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    timeout-minutes: 10
    steps:

# Build (Debug)

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build Debug
      run: dotnet build --configuration Debug --no-restore

# Test
    # Note: The --blame and VSTEST_DUMP_PATH stuff is needed to diagnose the test runner crashing on ubuntu/mac
    # See https://github.com/microsoft/vstest/issues/2952 for why the --blame stuff below is needed.
    # Without it, the test runner crashes on ubuntu (but not Windows or mac)

    - name: MacOS - Patch test runner settings to stop on fail
      if: runner.os == 'macOS'
      run: |
        brew install gnu-sed
        gsed -i 's/"stopOnFail": false/"stopOnFail": true/g' UnitTests/xunit.runner.json

    - name: Windows/Linux - Patch test runner settings to stop on fail
      if: runner.os != 'macOS'
      run: |
          sed -i 's/"stopOnFail": false/"stopOnFail": true/g' UnitTests/xunit.runner.json

    - name: Set VSTEST_DUMP_PATH
      shell: bash
      run: echo "{VSTEST_DUMP_PATH}={logs/${{ runner.os }}/}" >> $GITHUB_ENV

    - name: Run UnitTests
      run: |
       dotnet test UnitTests --verbosity normal --collect:"XPlat Code Coverage" --settings UnitTests/coverlet.runsettings --diag:logs/${{ runner.os }}/logs.txt --blame --blame-crash --blame-hang --blame-hang-timeout 60s --blame-crash-collect-always 
     
       # mv -v UnitTests/TestResults/*/*.* TestResults/UnitTests/

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-${{ runner.os }}
        path: |
          logs/    
          TestResults/UnitTests/
  

  build_release:
    # Ensure that RELEASE builds are not broken
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: Build Release Terminal.Gui
      run: dotnet build Terminal.Gui/Terminal.Gui.csproj --configuration Release

    - name: Pack Release Terminal.Gui
      run: dotnet pack Terminal.Gui/Terminal.Gui.csproj --configuration Release --output ./local_packages

    - name: Build Release Solution
      run: dotnet build --configuration Release
